server:
  port: 8080
spring:
  application:
    name: theater
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
  session:
    jdbc:
      initialize-schema: always
