export const URLS = [
    "/api/auth",
    "/api/auth/logout",
    "/api/auth/login",
    "/api/auth/register",
    "/api/auth/roles",
    "/api/auth/permissions",
    "/api/auth/current-user",
    "/api/auth/admin/register",
    "/api/locations",
    "/api/locations/$id",
    "/api/locations/$id/status",
    "/api/locations/$id/status",
    "/api/locations/$id/halls",
    "/api/halls",
    "/api/halls/$id",
    "/api/halls/$id/status",
    "/api/users",
    "/api/users/$username",
    "/api/users/$username/status",
    "/api/managers",
    "/api/managers/$username",
    "/api/managers/$username/status",
    "/api/movies",
    "/api/movies/$id",
    "/api/filter-options/cities",
    "/api/filter-options/countries",
] as const;
